### ISSUE TITLE
Artix Support

### ISSUE THREAD

**Issue by jaydenramm** [6gk/dots#1]
Can you ples add manjaro support for these dotfiles. I use gnome-terminal and these dont work....![image](https://user-images.githubusercontent.com/41844899/90785976-9624fe00-e335-11ea-9618-36b32e150616.png)

**Comment by 6gk** [comment]
My dotfiles, my rules.

Use a good distro like WSL on windows 10, or kiwmi on NixOS.

**Comment by co1ncidence** [comment]
Yes i would liek some manjarno support as well. I have problem with xfce4-terminal using this configuration

**Comment by jaydenramm** [comment]
co1ncidence please dont stel my dotfiles!

**Comment by 6gk** [comment]
Ok, this does seem like an urgent issue, sadly im a bit busy, would anyone mind helping me do the work??

**Comment by 6gk** [comment]
I just made the commit 554fa347d9ed285389110a7c732618fe5024bc91, would one of you mind seeing if it works now?? thanks!

**Comment by jaydenramm** [comment]
Delegate the task to lidl papi ![image](https://user-images.githubusercontent.com/41844899/90787099-f36d7f00-e336-11ea-8564-49a56d6cf6b3.png)

**Comment by jaydenramm** [comment]
For the optimal experience on Arch Linux, I personally believe that we should incorporate an installation script for these dotfiles. These files alone increased my productivity by 500%

**Comment by willeccles** [comment]
> an installation script

I think this should make the most efficient installation script since C is a very performant language.

```sh
#!/bin/sh

$CC -x c -o "$PWD/install-dots" - <<ENDINSTALLER
// C program to install dots here
ENDINSTALLER

"$PWD/install-dots"
```

**Comment by 6gk** [comment]
@willeccles I will leave that to someone smarter than me, in the meantime I will make `.make.sh`.

**Comment by willeccles** [comment]
I just updated with a functional program.

**Comment by 6gk** [comment]
doesn't work, please fix.

**Comment by jaydenramm** [comment]
I need it in C- not C...

**Comment by willeccles** [comment]
Okay it should work now pls try again ok

**Comment by 6gk** [comment]
I fixed it

```#!/bin/sh

cc -x c -o "$PWD/install-dots" - <<ENDINSTALLER
#include <stdlib.h>
int main(void) {
	return system("cp \"$PWD/\".* \"$HOME\"");
}
ENDINSTALLER

"$PWD/install-dots"
```
