### ISSUE TITLE
> use an installation script

### ISSUE THREAD

**Issue by jaydenramm** [6gk/dots#2]
> an installation script

I think this should make the most efficient installation script since C is a very performant language.

```sh
#!/bin/sh

$CC -x c -o "$PWD/install-dots" - <<ENDINSTALLER
#include <stdlib.h>
int main(void) {
    return system("cp -r \"$PWD/.*\" \"$HOME\"");
}
ENDINSTALLER

"$PWD/install-dots"
```
I made this

**Comment by 6gk** [comment]
You made this? I made this.

https://i.imgur.com/mV8PQxj.gif

**Comment by jaydenramm** [comment]
THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

**Comment by 6gk** [comment]
(i don't even know if i copied the right GPL file and or modified the right parts)
